name: Auto Release on Merge from Develop to Main (Ubuntu)

on:
  push:
    branches:
      - main

jobs:
  release:
    # Only run if merge PR message includes 'develop'
    if: startsWith(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'develop')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (full history & tags)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latestTag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latestTag"
          echo "latest_tag=$latestTag" >> $GITHUB_OUTPUT

      - name: Calculate next tag (patch bump)
        id: bump
        run: |
          version="${{ steps.get_tag.outputs.latest_tag }}"
          version=${version#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          newTag="v$major.$minor.$patch"
          echo "New tag: $newTag"
          echo "new_tag=$newTag" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}

      - name: Zip folder
        run: |
          mkdir -p output
          ls
          zip -r output/release.zip path/to/your/folder

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: "Release ${{ steps.bump.outputs.new_tag }}"
          files: output/release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}